"""weight"""
def main():
    """weight"""
    kon1 = input()
    www1 = float(input())
    hhh1 = float(input())
    kon2 = input()
    www2 = float(input())
    hhh2 = float(input())
    kon3 = input()
    www3 = float(input())
    hhh3 = float(input())
    kon4 = input()
    www4 = float(input())
    hhh4 = float(input())
    kon5 = input()
    www5 = float(input())
    hhh5 = float(input())
    print(kon1+"'s"+"  BMI", "=", "%.2f"%(www1/((hhh1/100)**2)))
    print(kon2+"'s"+"  BMI", "=", "%.2f"%(www2/((hhh2/100)**2)))
    print(kon3+"'s"+"  BMI", "=", "%.2f"%(www3/((hhh3/100)**2)))
    print(kon4+"'s"+"  BMI", "=", "%.2f"%(www4/((hhh4/100)**2)))
    print(kon5+"'s"+"  BMI", "=", "%.2f"%(www5/((hhh5/100)**2)))
main()
